import {useEffect,useMemo,useRef,useState} from 'react';
import {Button} from '@astryxdesign/core/Button';
import {BookOpen,Brain,ChevronRight,Clock,Focus,Headphones,Highlighter,MessageSquareText,PanelLeftClose,PanelRightClose,Pause,Play,Search,Sparkles,Target,Trophy} from 'lucide-react';
import {documentHtml,sections} from './data/rfc';

type Mode='read'|'focus'|'review';
export function App(){
 const [active,setActive]=useState(0); const [mode,setMode]=useState<Mode>('read'); const [speaking,setSpeaking]=useState(false); const [note,setNote]=useState(''); const [notes,setNotes]=useState<string[]>([]); const article=useRef<HTMLElement>(null);
 const progress=Math.round(((active+1)/sections.length)*100); const current=sections[active];
 useEffect(()=>{const el=document.getElementById(current.id); el?.scrollIntoView({behavior:'smooth',block:'start'});},[active]);
 const speak=()=>{if(!('speechSynthesis'in window))return;if(speaking){speechSynthesis.cancel();setSpeaking(false);return;}const text=article.current?.innerText??'';const u=new SpeechSynthesisUtterance(text);u.rate=.95;u.onend=()=>setSpeaking(false);speechSynthesis.speak(u);setSpeaking(true)};
 const addNote=()=>{if(!note.trim())return;setNotes(v=>[note.trim(),...v]);setNote('')};
 const summary=useMemo(()=>['The problem is inconsistent cross-team delivery contracts, not raw throughput.','NATS JetStream is preferred because organisational fit outweighs maximal capability.','The decision is reversible: Kafka remains an escalation path for demonstrated log-processing needs.'],[]);
 return <div className={`app mode-${mode}`}>
  <header className="topbar"><div className="brand"><div className="mark">M</div><span>Margin</span><em>prototype</em></div><div className="doc-title"><BookOpen size={15}/> RFC-014 · Event backbone selection</div><div className="top-actions"><button className="icon-button" title="Search"><Search size={17}/></button><Button label={mode==='focus'?'Exit focus':'Focus'} variant="secondary" onClick={()=>setMode(mode==='focus'?'read':'focus')}/><div className="avatar">RR</div></div></header>
  <main className="workspace">
   <aside className="left-rail"><div className="rail-heading"><span>Reading map</span><PanelLeftClose size={16}/></div><div className="mission"><Target size={17}/><div><b>Your mission</b><p>Test whether this decision still works at 40 teams.</p></div></div><nav>{sections.map((s,i)=><button key={s.id} onClick={()=>setActive(i)} className={i===active?'active':''}><span className="step">{i<active?'✓':s.number}</span><span><b>{s.title}</b><small>{s.kind} · {s.minutes} min</small></span></button>)}</nav><div className="momentum"><div><span>Argument progress</span><b>{progress}%</b></div><div className="progress"><i style={{width:`${progress}%`}}/></div><small>{sections.slice(0,active+1).reduce((a,s)=>a+s.minutes,0)} minutes invested</small></div></aside>
   <section className="reader-shell"><div className="reader-toolbar"><div className="mode-tabs"><button className={mode==='read'?'active':''} onClick={()=>setMode('read')}>Read</button><button className={mode==='review'?'active':''} onClick={()=>setMode('review')}>Review</button></div><div><button className={`tool ${speaking?'active':''}`} onClick={speak}>{speaking?<Pause size={16}/>:<Headphones size={16}/>} {speaking?'Pause':'Listen'}</button><button className="tool"><Highlighter size={16}/> Highlight</button></div></div>
    {mode==='review'?<div className="review-screen"><div className="review-header"><Trophy size={30}/><h1>Boss battle</h1><p>Prove you understood the decision rather than merely reaching the bottom.</p></div>{['Why is Kafka not the default despite its stronger ecosystem?','What behaviour must every consumer implement?','What evidence would trigger reconsidering this decision?'].map((q,i)=><div className="challenge" key={q}><span>0{i+1}</span><div><b>{q}</b><textarea placeholder="Answer in your own words…"/></div></div>)}</div>:<article ref={article} className="document" dangerouslySetInnerHTML={{__html:documentHtml}}/>}
    <div className="section-nav"><button disabled={active===0} onClick={()=>setActive(v=>Math.max(0,v-1))}>Previous</button><span>{current.number} / 05</span><button onClick={()=>active===sections.length-1?setMode('review'):setActive(v=>Math.min(sections.length-1,v+1))}>{active===sections.length-1?'Start review':'Next idea'} <ChevronRight size={16}/></button></div>
   </section>
   <aside className="right-rail"><div className="rail-heading"><span>Thinking companion</span><PanelRightClose size={16}/></div><section className="prompt-card"><div className="label"><Sparkles size={15}/> Before this section</div><h3>{current.question}</h3><button onClick={()=>setNote(current.question+' ')}>Capture a thought <ChevronRight size={14}/></button></section><section className="lens"><div className="label"><Brain size={15}/> Reasoning lens</div><div className="lens-row"><span className="dot claim"/><div><b>Claim</b><p>NATS is the best organisational fit.</p></div></div><div className="lens-row"><span className="dot evidence"/><div><b>Evidence</b><p>Small platform team; moderate scale.</p></div></div><div className="lens-row"><span className="dot risk"/><div><b>Risk</b><p>Ease of entry can hide contract complexity.</p></div></div></section><section className="notes"><div className="label"><MessageSquareText size={15}/> Margin notes</div><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Write what you think, not what the document says…"/><button onClick={addNote}>Save note</button>{notes.map((n,i)=><p key={i}>{n}</p>)}</section><section className="takeaways"><div className="label"><Focus size={15}/> Emerging model</div>{summary.map(s=><div className="takeaway" key={s}><span>•</span>{s}</div>)}</section></aside>
  </main><footer><span><Clock size={14}/> 27 min estimated</span><span>Autosaved locally</span><span>Markdown · UTF-8</span></footer>
 </div>
}
